### ISSUE TITLE
segmentation fault problem and Examples

### ISSUE THREAD

**Issue by lVentus** [System64fumo/sysmenu#2]
When I try to run it, it always has segmentation fault (core dumpd) problems.
I don't know how to solve it.
And how do you config for the 2 examples? I really like them and want to use them for my 2in1.
But I didn't find any in your dots file, Would you like to share them?
Thanks!

**Comment by System64fumo** [comment]
I think i've heard of this before? Try updating gtkmm 4.0 and gtk4
As for the fullscreen example this is what i use on my desktop: ``sysmenu -p 6 -m 10 -i 64 -u -n 15 -fS``

**Comment by lVentus** [comment]
> I think i've heard of this before? Try updating gtkmm 4.0 and gtk4 As for the fullscreen example this is what i use on my desktop: `sysmenu -p 6 -m 10 -i 64 -u -n 15 -fS`

I am using 4.14, which is newest release. First I thought it may be a problem because of hyprland, but in sway I got same problem.

**Comment by System64fumo** [comment]
That is odd, Are you able to run any of my other sys programs?
Try [syspower](https://github.com/System64fumo/syspower), this is the least complex program i have.
If you can't run that try running any other gtkmm 4.0 program you can find

If you want to try something real quick, Try cloning this repo and edit the makefile to not have `-march=native -mtune=native` then compile it

**Comment by System64fumo** [comment]
@lVentus Could you check now?
I think i fixed this in 8b1f1f0dd8291c322b8527239d1487310f55ebc8

**Comment by System64fumo** [comment]
Considering this fixed unless stated otherwise.
