### ISSUE TITLE
Compilation Errors: Gtk::FlowBox missing 'remove_all' and 'get_children' methods

### ISSUE THREAD

**Issue by MalcolmReed-ent** [System64fumo/sysmenu#3]
**Environment:**
- **Distro:** Debian Sid
- **Dependencies Installed:** 
  - libgtkmm-4.0-dev
  - libgtk4-layer-shell-dev
- **Compiler:** gcc (Debian 13.3.0-1) 13.3.0

**Error:**
**Compilation Command:**
g++ -c src/window.cpp -o src/window.o
-march=native -mtune=native -Os -s -Wall -flto=auto -fno-exceptions -fPIC
-I/usr/include/gtkmm-4.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-4.0/include
-I/usr/include/giomm-2.68 -I/usr/lib/x86_64-linux-gnu/giomm-2.68/include
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
-I/usr/include/sysprof-6 -I/usr/include/libmount -I/usr/include/blkid
-I/usr/include/glibmm-2.68 -I/usr/lib/x86_64-linux-gnu/glibmm-2.68/include
-I/usr/include/sigc++-3.0 -I/usr/lib/x86_64-linux-gnu/sigc++-3.0/include
-I/usr/include/gtk-4.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz
-I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/fribidi
-I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0
-I/usr/include/x86_64-linux-gnu -I/usr/include/webp -I/usr/include/graphene-1.0
-I/usr/lib/x86_64-linux-gnu/graphene-1.0/include -I/usr/include/cairomm-1.16
-I/usr/lib/x86_64-linux-gnu/cairomm-1.16/include -I/usr/include/pangomm-2.48
-I/usr/lib/x86_64-linux-gnu/pangomm-2.48/include -I/usr/include/gtk-4.0/unix-print
-I/usr/include/gtk4-layer-shell -mfpmath=sse -msse -msse2 -pthread

**Error 1:**
src/window.cpp: In member function 'void sysmenu::app_info_changed(GAppInfoMonitor*)':
src/window.cpp:14:25: error: 'class Gtk::FlowBox' has no member named 'remove_all'; did you mean 'remove_data'?
14 | flowbox_itembox.remove_all();
| ^~~~~~~~~~
| remove_data

**Error 2:**
src/window.cpp: In member function 'bool sysmenu::on_escape_key_press(const guint&, const guint&, const Gdk::ModifierType&)':
src/window.cpp:179:57: error: 'class Gtk::FlowBox' has no member named 'get_children'
179 | auto children = flowbox_itembox.get_children();
| ^~~~~~~~~~~~

**Make Error:**
 make: *** [Makefile:35: src/window.o] Error 1

**Comment by System64fumo** [comment]
I've seen this issue on arch too, You need to use the latest version of gtkmm 4 (gtkmm 4.14)
On sid the latest version of gtkmm is 4.10 as far as i can tell.

**Comment by MalcolmReed-ent** [comment]
Thanks for the info. You're right, I'm currently using an older version of gtkmm 4 on Debian Sid. Specifically, I have: 

**libgtkmm-4.0-0/unstable,now 4.10.0-4+b2 amd64 [installed,automatic]**
