### ISSUE TITLE
remembering last launched applications?

### ISSUE THREAD

**Issue by koutsie** [System64fumo/sysmenu#4]
would it be possible to implement remembering the last X launched applications?

**Comment by System64fumo** [comment]
Sure sounds easy to implement, Will gladly take a look at it tomorrow when i get a chance.

**Comment by System64fumo** [comment]
@koutsie Tomorrow could also mean 2 in the morning, Consider your feature request "complete"
For now the history does not persist so whenever you close the menu or restart your pc the history gets wiped.
I'm tempted to add a history file hoooowever i don't feel like that's necessary, Totally down to add it if you consider it necessary.

Let me know what you think.

**Comment by System64fumo** [comment]
Forgot to mention but the history isn't sorted by how recently you launched the program.
Too much work to add a filter like that. (Big excuse because i'm lazy)

**Comment by koutsie** [comment]
It'd be more https://codeberg.org/dnkl/fuzzel like with history yeah - I'm too tired to think how to implement that properly haha

**Comment by System64fumo** [comment]
I think this is ready so gonna close this issue, Feel free to suggest better implementations if you come up with any in the future :+1:
