### ISSUE TITLE
SIGSEGV when launching on archlinux

### ISSUE THREAD

**Issue by Quackdoc** [System64fumo/sysmenu#5]
Trying to compile and run on archlinux and I am getting a sigsegv, I have tried mutter, kwin, cosmic, and niri

I ran in gdb and got the following backtrace

```hx
#0  0x00007ffff7ce8e14 in Gtk::FlowBox::remove_all() () at /usr/lib/libgtkmm-4.0.so.0
#1  0x00007ffff0045ed7 in sysmenu::app_info_changed(_GAppInfoMonitor*) () at /usr/lib/libsysmenu.so
#2  0x00007ffff646ec34 in std::execute_native_thread_routine (__p=0x555555c30d20) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:104
#3  0x00007ffff611339d in ??? () at /usr/lib/libc.so.6
#4  0x00007ffff619849c in ??? () at /usr/lib/libc.so.6
```

I checked in another thread and you mentioned testing syspower, syspower works fine

**Comment by System64fumo** [comment]
Oh.. What a silly mistake.. Pushed a fix for that :|
Whoopsies!

Let me know if that fixed it @Quackdoc

**Comment by Quackdoc** [comment]
hmm, seem to be having the same issue still. 

EDIT: It did seem to work, I had a dirty file that was getting picked up, thanks!

**Comment by System64fumo** [comment]
Splendid :+1:
